### ISSUE TITLE
The loading icon is not hidden after installation

### ISSUE THREAD

**Issue by j4ndr4** [pinry/pinry#100]
The variable API_LIMIT_PER_PAGE isn't available in the template base.html. I hardcoded the value and now it works fine.

The loading icon kept visible all the time. I wasn't able to pin a new image so I checked the javascript console and found that there was a javascript error.

Also, minor suggestion: adding this info in the technical documentation about how to add a new user from the terminal: bin/python manage.py createsuperuser

Thank you for this project!!!!

**Comment by overshard** [comment]
Fixed in 2d8d92b, the context_processor for template_settings wasn't being loaded.
