### ISSUE TITLE
Setting the domain for Pinry?

### ISSUE THREAD

**Issue by Flamekebab** [pinry/pinry#102]
I can't run Docker at the moment (OpenVZ issue) so I'm trying to get Pinry running as a development server. It seems happy to run locally but I can't find any documentation to tell me how to change where it runs. I have a Apache2 up but I'm not sure how to set things up so that visiting a directory on my domain will access Pinry.

`Performing system checks...

System check identified no issues (0 silenced).
February 17, 2017 - 15:53:43
Django version 1.8.17, using settings 'pinry.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.`

I thought perhaps by accessing the domain at port 8000 with ALLOWED_HOSTS = ['*'] would work but no such luck.

Can someone point me in the right direction?

**Comment by overshard** [comment]
If you wish to get access to the development server from a remote computer you need to run "python manage.py runserver 0.0.0.0:8000", by default the development django server locks down all access except for localhost.

If you wish to run Pinry with Apache you can follow the Django instructions here: https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/modwsgi/
