### ISSUE TITLE
Quality settings for PIL in the settings file?

### ISSUE THREAD

**Issue by Flamekebab** [pinry/pinry#106]
In settings.py we can set image sizes but is there somewhere obvious to change JPEG settings?
I'm not happy with the defaults and would rather burn a bit more disk space in exchange for higher quality.

**Comment by overshard** [comment]
I did not code the image system for Pinry 1.x but I believe that is handled by django-images and we have no direct way to change it. I'll make note of this for Pinry 2.x and leave this isue open to make sure we give people that option!

**Comment by Flamekebab** [comment]
Should I be running Pinry 2.x ?

From what I can see there's a few different places that might be where the quality settings are stored. `.venv/lib/python2.7/site-packages/django_images/utils.py` seems to be where django-images stores something relevant. PIL has a settings file here: `.venv/lib/python2.7/site-packages/PIL/JpegPresets.py`

I'm not really sure where the .pyc files come into things. If I understand correctly they're sort of compiled Python which makes me wonder whether one needs to recompile the settings files before they take effect. Bit on the ignorant side here, I'm afraid.

My ignorance extends further into `pilconvert.py` which seems to have some sort of quality option on line 82.

Also it looks like deleting pins doesn't delete the uploaded file or its generated variants. On the plus side it does keep the original file even if it doesn't show it on the front end anywhere. I'd like to be able to view that too, ideally ("view original image" or similar).

**Comment by overshard** [comment]
No, Pinry 2.x isn't anywhere near being useful yet unfortunately.

The files you are pointing out are all out of our control unfortunately, they are separate apps that we import essentially. We can't change imported applications easily. The PYC files are useless, it's just python bytecode that compiles at runtime and you never really touch them by hand.

As I was saying before though all images are handled by a third-party app https://github.com/mirumee/django-images

I'm not sure we have any control over image thumbnail quality in this app but I haven't looked closely at it.

**Comment by Flamekebab** [comment]
Good news! I've just had a look at the django-images documentation and saw something I recognised:

`# settings.py
IMAGE_SIZES = {
    'normal': {
        'size': (500, 0),
        'quality': 85
    },
    'tiny_square': {
        'size': (100, 100),
        'crop': True
    }
}`

In Pinry's settings.py file there's this:

`IMAGE_SIZES = {
    'thumbnail': {'size': [240, 0]},
    'standard': {'size': [600, 0]},
    'square': {'crop': True, 'size': [125, 125]},
}`

I'd previously changed my "standard" size to 800 as 600 seemed a bit small and that worked immediately.

This is how the quality is changed:
`IMAGE_SIZES = {
    'thumbnail': {'size': [240, 0]},
    'standard': {'size': [800, 0], 'quality': 10},
    'square': {'crop': True, 'size': [125, 125]},
}`

That sets it to a terrible quality, of course, but it's a quick way to see it's working. From there the quality setting can be changed to whatever.

**Comment by overshard** [comment]
Sounds good! I'll add this to the readme in case anyone else wants to do the same.
