### ISSUE TITLE
Bookmarklet: add support for background images

### ISSUE THREAD

**Issue by lapo-luchini** [pinry/pinry#109]
A few websites and galleries do use `background-image` style to put images (well, the bookmarklet itself does it), so I updated the bookmarklet to load those as well. It does need to iterate over many tags in the page, but does seem to work pretty ok, do you think it would be interesting to integrate?
I could cherry-pick lapo-luchini@1d9700585eee2c8faa97cc2b8c6f7019a189d85e and create a Pull Request.

**Comment by lapo-luchini** [comment]
Do you think this is interesting? I can create the PR if needs be.
(else I'll keep it on my branch / local install)

**Comment by winkidney** [comment]
It's versy awesome and it's a client-only feature.
PR is very welcome!

**Comment by winkidney** [comment]
Is there any performance issue on this feature?

**Comment by lapo-luchini** [comment]
Closed by #213.
