### ISSUE TITLE
how to modify tiles positioning on phones?

### ISSUE THREAD

**Issue by zzm88** [pinry/pinry#110]
default is showing one row only rather than two rows auto resizing to fit out the screen's width (like pinterest did) . how to implement this effect?

**Comment by winkidney** [comment]
"media query" may be what you want.

It's difficult for Pinry to implemet this feature because we have'nt organize our code by bootstrap or other responsive framework.

Pull Request is always welcome.

**Comment by overshard** [comment]
This is just personal preference and can be changed via a styling update. There are two columns on horizontal phone and up.
