### ISSUE TITLE
No way to change password?

### ISSUE THREAD

**Issue by Flamekebab** [pinry/pinry#112]
I'm setting up a private board and want to create a few accounts for friends and then close registrations. I was going to generate passwords which they could then change to something they prefer but as far as I can tell there's no way to change passwords. Am I just missing where that's done?

**Comment by winkidney** [comment]
Currently we can only change the password via django-admin panel.

**Comment by philiptruax** [comment]
@winkidney Perhaps a workaround documentation is needed for how to do this or at least a pointer to how one would do this in Django as this is a rather expected feature at this point.

**Comment by overshard** [comment]
http://docs.getpinry.com/passwords/

I've added docs on this.
