### ISSUE TITLE
from cStringIO import StringIO

### ISSUE THREAD

**Issue by snowmanninja** [pinry/pinry#114]
Hello, 

I am looking at the master branch and it references to cStringIO but as far as I was aware it is no longer a thing in python? is there a specific version of python you're using like <3.5 or is this an external file missing from github or could this be replaced with IO from python3+ or would that cause too many issues

**Comment by overshard** [comment]
This project hasn't been updated in a while, the version we tested on was 2.6, It should work on 2.7 and anything 3+ will probably fail.

**Comment by snowmanninja** [comment]
ah that explains allot of the errors I was seeing Cheers
