### ISSUE TITLE
 rjsmin/rcssmin install error

### ISSUE THREAD

**Issue by IvanZaro** [pinry/pinry#115]
Hi,

I'm trying to install app but getting errors.
When i run   **pip install django-compressor --upgrade**  i got:

 **Requirement already up-to-date: django-compressor in /home/FBL/anaconda3/lib/python3.5/site-packages
Requirement already up-to-date: rjsmin==1.0.12 in /home/FBL/anaconda3/lib/python3.5/site-packages (from django-compressor)
Requirement already up-to-date: django-appconf>=1.0 in /home/FBL/anaconda3/lib/python3.5/site-packages (from django-compressor)
Requirement already up-to-date: rcssmin==1.0.6 in /home/FBL/anaconda3/lib/python3.5/site-packages (from django-compressor)**
 
and if i run 
 **bin/pip install -r requirements.txt**

Building wheels for collected packages: rjsmin, rcssmin
  Running setup.py bdist_wheel for rjsmin ... error
  Complete output from command /mnt/c/Users/FBL/Desktop/pinry-master/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-60Vd4g/rjsmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmphy4XHDpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying ./rjsmin.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_rjsmin' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DEXT_MODULE=_rjsmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python2.7 -c rjsmin.c -o build/temp.linux-x86_64-2.7/rjsmin.o
  In file included from rjsmin.c:18:0:
  _setup/include/cext.h:34:20: fatal error: Python.h: Nema takve datoteke ili direktorija
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for rjsmin
  Running setup.py clean for rjsmin
  Running setup.py bdist_wheel for rcssmin ... error
  Complete output from command /mnt/c/Users/FBL/Desktop/pinry-master/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-60Vd4g/rcssmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpHKoKo8pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying ./rcssmin.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_rcssmin' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DEXT_MODULE=_rcssmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python2.7 -c rcssmin.c -o build/temp.linux-x86_64-2.7/rcssmin.o
  In file included from rcssmin.c:18:0:
  _setup/include/cext.h:34:20: fatal error: Python.h: Nema takve datoteke ili direktorija
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for rcssmin
  Running setup.py clean for rcssmin
Failed to build rjsmin rcssmin
Installing collected packages: rjsmin, rcssmin, django-appconf, django-compressor, python-mimeparse, six, python-dateutil, django-tastypie, funcsigs, pbr, mock, factory-boy
  Running setup.py install for rjsmin ... error
    Complete output from command /mnt/c/Users/FBL/Desktop/pinry-master/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-60Vd4g/rjsmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fgygjI-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/Users/FBL/Desktop/pinry-master/include/site/python2.7/rjsmin:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying ./rjsmin.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_rjsmin' extension
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DEXT_MODULE=_rjsmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python2.7 -c rjsmin.c -o build/temp.linux-x86_64-2.7/rjsmin.o
    In file included from rjsmin.c:18:0:
    _setup/include/cext.h:34:20: fatal error: Python.h: Nema takve datoteke ili direktorija
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/mnt/c/Users/FBL/Desktop/pinry-master/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-60Vd4g/rjsmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fgygjI-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/Users/FBL/Desktop/pinry-master/include/site/python2.7/rjsmin" failed with error code 1 in /tmp/pip-build-60Vd4g/rjsmin/

Please help

**Comment by overshard** [comment]
It looks like you don't have build essentials installed:

`sudo apt install build-essential`

**Comment by overshard** [comment]
Note, you may also need python-dev or python3dev:

`sudo apt install python3-dev`

**Comment by IvanZaro** [comment]
THX

2017-09-23 23:06 GMT+02:00 Isaac Bythewood <notifications@github.com>:
