### ISSUE TITLE
Images with strange URLs do no work

### ISSUE THREAD

**Issue by lapo-luchini** [pinry/pinry#125]
While copying an image from one Pinry install to another, I tried using an image URL (copied from browser) that ended with:
`…/DWBYNR2VMAABhdD.png%3Alarge`
It was saved on disk as:
`demo/static/media/9/8/98bf2d720e7101223eb2d8da3f80ec80/DWBYNR2VMAABhdD.png%3Alarge`
But it was not visible in the interface.
I guess we should clean the filename or at least add the correct extension as detected from the image format.

**Comment by willstott101** [comment]
To add to this the URLs when uploading are validated by Django [https://github.com/django/django/blob/55b68de643b5c2d5f0a8ea7587ab3b2966021ccc/tests/validators/valid_urls.txt](See this set of valid urls.) But this isn't completely inclusive.

It fails for very simple hostnames like `http://localserver/my/cool/images/foobar.png`. Could the validation instead be the error from whatever library fetches the image?

**Comment by winkidney** [comment]
@willstott101 A new change has been pushed to allow any type of url (simply use CharField instead of URLField).
https://github.com/pinry/pinry/commit/e216e5a6f2d62c068bc7d6eda70135cb9055482b
This change may cause XSS issue but Pinry is a private pin-board now, I'm not sure if it make sense for us to use complex protection for it, FYI.
Feel free to tell us if you have any further question or advice, thanks!

**Comment by willstott101** [comment]
Ah thanks @winkidney I actually ended up monkey-patching the regex to specifically support that form of URL (in the local settings py... :S). I should probably take the time to search for other people affected and follow this up in upstream Django. There are definitely some URLs in their invalid test that I'm surprised to see there.

This is a perfectly reasonable solution for me. Is the XSS you're thinking of going to be `javascript:` hrefs? Or are some of these URLs actually embedded? I suppose SVGs might be a consideration... perhaps we ought to suggest hosting media under a separate domain (pretty trivial on an intranet). Maybe supported directly by standard Django settings.

**Comment by winkidney** [comment]
@willstott101 

The url or referer we display for Pin objects without any escape.
But for private usage, it will not cause any problem, so If we have better solution for it, we may make a better fix.

Maybe you could make a patch to django-project and they will accept them.
RFC may be the reason if they decline to accept this change, haha.
