### ISSUE TITLE
Suggestion: Add screenshots

### ISSUE THREAD

**Issue by sbrl** [pinry/pinry#132]
Pinry looks great, but it's hard for newcomers to see what it looks like with a demo instance (which can attract spam).

In light of this, I suggest adding some screenshots instead. Perhaps a new page on the main website?

This will help new potential users to see what it looks like before they try installing it for themselves.

**Comment by sbrl** [comment]
Ah, thanks!

And it does look like Pinry, doesn't it? Now that I look at your instance, I can tell that now. I don't think it's obvious that the background image is, infact, Pinry though.

Perhaps on the main website's nav bar, a new "screenshots" page could be added? Perhaps `About, Screenshots, Docs, Issues, GitHub`? If that's not possible then a section on the _About_ page would work too I think.

**Comment by winkidney** [comment]
Sounds good for me, thanks for your advice.
Any idea or tips about update the main site @overshard ?

I will add  a page named screenshot once I have time.

**Comment by overshard** [comment]
I think a screenshots page would be useful. I don't really want to host a public instance to have people play with it so I think that would be optimal. The only problem is just keeping the screenshots up-to-date.

**Comment by overshard** [comment]
I've added a screenshots page to the docs so we can start adding items to it, closing this out, if anyone wants to submit screenshots it's pretty self explanatory and we accept pull requests!
