### ISSUE TITLE
Discuss: another way to organize pins, just like "board" or "topic"

### ISSUE THREAD

**Issue by winkidney** [pinry/pinry#133]
Hi,

I'd like to add a new way to organize our pins and ideas, for better sharing, better way to show your ideas.

## Why
If  we want to organize our pins, at first we give it tags, then we can access specified tag to get our previously saved pins.

If we want to share specified set of pins which includes pins about characters, scenes, models, with same style or some shared properties with many different tags (e.g "ideas to make act-game"  maybe), it's hard for us to do that.
As a result, I'd like to add a set-like concept to organize pins that way.

## How

We can just add a "set"(named board or topic, anyway) in our Pinry system, we can add some pins to this "set", then share it to others.

For Django, it's a new model named "Topic" or "Board" which has many2many field targets to Pin.

## Other feature Advices
+ tag list: Maybe we need a page to show all of the tags and give links to each of them
+ search: by tag or name, view by multiple tags (like pinterest)

What do you think about this feature? @overshard 

 related: #141

**Comment by overshard** [comment]
A set or board makes sense to me as a split from tags. Tags may contain lots of random details and a board could contain a more over-arching grand idea. I do think it is slightly redundant with tags if tags were possibly better organized and easier to pick out but maybe I am wrong here.

I'm fine with there being a Set/Board/Topic categorization structure. I also do agree that tags and search needs to be implemented or improved upon since it's really difficult to find some very old tags or images at this time.

**Comment by winkidney** [comment]
@overshard LOL I have the same position before today, I thought that tags is enough for us to store ideas.

My friend who using my Pinry instance tells me that thier disigner want some reference for their game-making.I have no idea to give her a way to combine all of the pins she want and realize that maybe a "set" or "board" can resolve this problem for us.

IMO, tags each other should be flattening, so a "set" is better for us to organize a "topic". 

We may add a guide or some tips to tell users how should thay use "set", what's the difference between tags.

That make sense for me and other possible users, haha.

Thanks for your fast reply.
Best regards.

**Comment by overshard** [comment]
Boards/Sets have been a topic that come up every now and then, when so many people requesting it it probably should be implemented. I think it's just how people are used to organizing things on other platforms and they don't understand the tagging aspect.

**Comment by overshard** [comment]
I think that's fine. I'd probably use the field even though tags cover a similar use case just because I often do have a "main tag" and then a bunch of secondary descriptor tags.

**Comment by winkidney** [comment]
I will try to implement it once I have time : )

**Comment by willstott101** [comment]
On the topic of what's the difference between tags and Boards... The Board could easily accrue many more fields over it's lifetime, essentially allowing any users to create their own mini Pinry instances. On that note I think it would make sense for the homepage to be it's own `ID=1` Board. In the future per-board permissions could then be very useful, allowing only admins/specific moderators to control the home page... etc

Is that consistent with your visions for Pinry?

**Comment by winkidney** [comment]
@willstott101 Board is more a topic than tag, a different dimension to organize pins, you could access any board or any home-page of specified owner as you like.
But the home page is not for specified user, its for all public pins.
I can't image the sense which we want to set home page to the home page of specified user, could you please give me an example?
Thanks.

**Comment by overshard** [comment]
I agree with @winkidney here, for an example a board can be a topic like "cars" and a tag would be more of specifics like "mustang, red, convertible" describing the attributes of the car or the type.

Of course the topic could also be "Mustang" or "Red" or "Convertible" in which case a tag could be "Cars" on that but it's an overall theme.

This would also open up options for fine tuning user control around boards. We can have users x, y, and z. x and y can add to and edit the "Cars" board but user "z" can only read it.

**Comment by willstott101** [comment]
Yes I don't disagree with any of this. I don't think I'm explaining myself very well.

My main motivator is being able to re-order pins on any board (via a through model), and by making the home page a board the reordering is possible there too.

I then had a secondary thought about boards having independent permissions, which would work nicely in a more organised setting where different departments can have permissions to post on their specific boards.

With both of those patterns in place, I think it could then make sense for the landing page to be carefully curated by a specific user or group of users. Once an instance is split into these separate sub boards, I think the homepage being a total dumping ground of everything is very unlikely to be useful.

However thinking about this again, I think just being able to choose an existing board as home page would be more intuitive and flexible.

**Comment by philiptruax** [comment]
A hopefully explanation of the tags versus boards explanation.

With tags your citing topics that connect across multiple different boards. 
With boards you're collecting a group of tags related to a specific project. 

In essence you could use a tagging/board system to create a modified form of a [Zettlekasten](https://zoia.org/2018/11/13/zettelkasten/) using images or even pictures of notecards and share them publicly. 

The boards function as a box or collection point for tightly related images.
The tags show interconnectedness between the boxes and ideas.

**Comment by lapo-luchini** [comment]
> However thinking about this again, I think just being able to choose an existing board as home page would be more intuitive and flexible.

As I was suggesting in #52 it would be nice to have pins with a specific tags being visible in the homepage (and publicly, possibly)… that's more or less the same idea as "tags used as boards" (and then sharing "tag-filtered links" instead of board) but of course, if anybody is up for doing it (and #141 tell me someone is) all the better? ;)

**Comment by overshard** [comment]
This has been implemented in @winkidney 's latest release. Going to add docs!

**Comment by overshard** [comment]
http://docs.getpinry.com/theories/
