### ISSUE TITLE
Placeholder on the docs page

### ISSUE THREAD

**Issue by slavniyteo** [pinry/pinry#135]
Hi. I've noticed that the [docs](https://pinry.readthedocs.io/en/latest/) link on the  [main page](https://getpinry.com) is related to placeholder instead of actual documentation.

It it is ok and docs are coming soon, just close the issue.

**Comment by winkidney** [comment]
Thanks for your issue.
Our doc now is hosted by github's markdown file. The link is outdated now, I will fix it once I have time.
Please read instructions at https://github.com/pinry/pinry to do the installation.

Feel free to contact us if you have any problem on setup or usage of Pinry.

**Comment by philiptruax** [comment]
I added the update, was the lack of documentation outside of Github due to time or some other issues?

**Comment by philiptruax** [comment]
As an aside was there a desire to write up docs? I could help with this if there was a place to put it specified. I'm not sure that GitHub would be that place though if you're looking for comprehensive documentation.

**Comment by winkidney** [comment]
Thanks for you help @philiptruax !

Since I have no access to offical-site, @overshard could you please put the latest version of doc to Pinry's web-host to fix the doc link?

**Comment by overshard** [comment]
I've updated the docs to publish directly from this repo to gh-pages now and am ditching the old repo/site for docs. New docs can be found at https://docs.getPinry.com/ and in the folder `docs` directly in this project. This should make the experience nicer to read documentation.
