### ISSUE TITLE
Problem saving image how to solve it

### ISSUE THREAD

**Issue by OrangeIUH** [pinry/pinry#144]
When I add one pic .
![image](https://user-images.githubusercontent.com/44519711/56490585-499a9a00-6518-11e9-9391-03bc5a649588.png)
and message appears 'Problem saving image'
![image](https://user-images.githubusercontent.com/44519711/56490650-75b61b00-6518-11e9-88fe-3f93cbb9b1e9.png)
![image](https://user-images.githubusercontent.com/44519711/56490660-7d75bf80-6518-11e9-9e67-33781d44c3a7.png)

**Comment by winkidney** [comment]
# Problem saving
Hi, when you meet the "Problem saving image", what's the method for you to create pin, upload or create from url?
Please provide more information for me to find out the issue.

# 404 favicon
This is not a problem, just ignore it.

**Comment by winkidney** [comment]
I have updated my online-demo to latest version and didn't found any problem like yours.

Would you like to provide some more information about your setup and environments ?

**Comment by OrangeIUH** [comment]
> I have updated my online-demo to latest version and didn't found any problem like yours.
> 
> Would you like to provide some more information about your setup and environments ?

I run it in Windows 10.
![image](https://user-images.githubusercontent.com/44519711/56845739-68be7080-68f8-11e9-980c-5a7cf2a236c3.png)
I can upload picture.One problem is when I add word in 'referer ', then occurs  'Problem saving image'.
like this.
![image](https://user-images.githubusercontent.com/44519711/56845770-db2f5080-68f8-11e9-80f4-18777444c523.png)
If I don't  use 'referer',it will be ok.
![image](https://user-images.githubusercontent.com/44519711/56845785-074ad180-68f9-11e9-862d-c12efef86339.png)

**Comment by OrangeIUH** [comment]
> I have updated my online-demo to latest version and didn't found any problem like yours.
> 
> Would you like to provide some more information about your setup and environments ?

More...
when I add word in "referer", 'Problem saving image' occurs, but the image has been in 'static' file folder and record(image name) in database.

**Comment by winkidney** [comment]
Thanks for your information. 
I found that you use normal string in referer but the referer should be an URL started with "http://" or "https".

I will add a place holder on this field to tell users what to fill.

**Comment by winkidney** [comment]
Placeholder the input-type has been changed to tell users it should be "url", this issue will be closed.
Feel free to reopen it if you have any further problem.
