### ISSUE TITLE
building from Dockerfile.autobuild fails to give execute permission to entrypoint scripts

### ISSUE THREAD

**Issue by norweeg** [pinry/pinry#146]
Built the image from Dockerfile.autobuild.  The scripts in /scripts of the resulting image have 644 permissions instead of 755 and cannot be executed

**Comment by winkidney** [comment]
I will check that once I have time, thanks for your feedback.

Please follow the guide in README to build the docker first.
Once I have correct the error/failure, I will update this issue.

**Comment by MingyJ** [comment]
I ran "find /home/pinry/ -type f -iname "*.sh" -exec chmod +x {} \;" to fix the issue but it took me a good 5 minutes to figure out what was failing. Otherwise it's working great!

**Comment by norweeg** [comment]
@winkidney built it using your scripts and, expected, same result.  By the way, why do your build scripts get the current user id and then sudo the current user id to build?  You are already the current user.  This is redundant
