### ISSUE TITLE
problem uploading image

### ISSUE THREAD

**Issue by t1v0** [pinry/pinry#156]
I tried to set up pinry myself using apache and mod_wsgi and I got the server running but could post any pins - kept getting an error 'proplem saving image'.  Looking at the requests I could see that any call to /api/v2/... was returning a 403 error.

Thinking that maybe it was my lack of knowledge of django and how to set it up I blew everything away, re-cloned it and then used the docker image.  I still get the same issue - 'problem saving image'.  As with the original instance all requests to /api/v2/... are returning a 403 forbidden error code.

**Comment by winkidney** [comment]
Maybe csrf token is missing?

**Comment by overshard** [comment]
We are using a new front-end for Pinry, please try that and let us know if you have any problems with it instead.
