### ISSUE TITLE
Python Imaging Library

### ISSUE THREAD

**Issue by MingyJ** [pinry/pinry#159]
To get this to work after running "make bootstrap" I had do manually rename the PIL folder in 

C:\Users\username\.virtualenvs\pinry-master-GvTIGkmg\Lib\site-packages

to "pil" re-run "make bootstrap" and then re-rename the folder "PIL" before running "make serve." 

Now with it up and running I do not have anything other than that (my memory) to go off.

**Comment by winkidney** [comment]
Pillow or PIL?
Description for your first package name is missing , could you please give me a complete one?
rename `C:\Users\username.virtualenvs\pinry-master-GvTIGkmg\Lib\site-packages` to "pil" makes me a little confuse : )

**Comment by overshard** [comment]
Having just installed this on a completely fresh system I'm not running into any issues. I did just update dependencies though on the project. I'm closing this unless we get some more information.
