### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by Flamekebab** [pinry/pinry#172]
I don't use Docker and I've had Pinry running for quite some time. With all the recent development I'd like to upgrade from whatever version I'm running (where would I check that? It looks like it's from February 2017 by timestamps) but I don't want to just overwrite my existing files and hope for the best - unless that's what I'm supposed to be doing?

Or would it make sense to output all the existing pins as a CSV or something, install clean, then import them somehow, assuming that's now possible?

**Comment by winkidney** [comment]
What's your version are you using?

If it's 1.x, You could checkout [Tag-2.0.1](https://github.com/pinry/pinry/tree/v2.0.1) and follow this [Guide](https://github.com/pinry/pinry/blob/v2.0.1/doc/upgrade_from_1.x.md) to upgrade to version-2.0.1.

After all job has done, you could upgrade to the latest version with almost no extra actions(just checkout the latest, do migrate, then start new server).

And, you should build frontend yourself (or with our docker: `docker-compose up build_fronted`, it will build frontend-files in `pinry-spa/dist/`)

Then copy these files to your nginx html root.

And another point is that: you have to run `pipenv run python manage.py collectstatic` again to collect latest bookemarklet.js.

Last but not least important, please backup all database data before your upgrade operations.

Feel free to contact me if you have any problem on upgrade process.

**Comment by winkidney** [comment]
@Flamekebab I have created a discord channel for pinry-users: https://discord.gg/vGuaYpp

If you have any question or problem, feel free for contact us.

We will respond you once we have free time.

**Comment by winkidney** [comment]
You could get your version with git log (and give us the first hash occurs on top).

**Comment by winkidney** [comment]
No further comments, closed.
Feel free to reopen it if you have any problem.
