### ISSUE TITLE
Frontend doesn't work with Chrome browser(maybe not related to browser but client cache)

### ISSUE THREAD

**Issue by MaciekBaron** [pinry/pinry#182]
I've tried installing Pinry following the steps in the documentation.

https://docs.getpinry.com/install-with-docker/

I visit my instance.

I register an account. Nothing changes, page refreshes. No errors.

Try logging in with the details I just registered. Nothing changes. No errors. It still says "Sign up" and "Login" at the top. Behaves exactly the same way if I enter invalid login details.

If I try to use the Pinry Extensions/Bookmarklet, choose an image, it takes me to a blank page. No errors in console. Just a blank page with the creme background color.

`/api/v2/profile/users/` returns an empty array (`[]`)

What am I missing here?

**Comment by MaciekBaron** [comment]
Ran `bash` on my docker instance.

Checked `/data/nginx-error.log`. Just errors about the favicon and `logo-dark.png`.

`/api/v2/docs/` returns a 500 error.

If I enter an invalid password, sometimes it briefly shows an error message and then refreshes the window, or sometimes it stays on. Authorisation seems to sort of work as when I do enter a wrong password and get the red error message, entering a correct password refreshes the page (but doesn't log me in). It's unclear to me why and when either of these scenarios happen. Sometimes if I enter random characters the page refreshes itself without even displaying an error message.

I think the core of the problem here is that `/api/v2/profile/users/` return an empty array.

Not sure what else to check...

**Comment by winkidney** [comment]
Have you ever signed up?
Is there any log for 500 error in docker?

You could get docker logs via comand `sudo docker logs <docker-container-id>`.
Please paste error logs and we could help.

**Comment by winkidney** [comment]
If you need more help, you could join our discord channel which described in https://github.com/pinry/pinry/issues/174

**Comment by MaciekBaron** [comment]
Logs don't show any issues I'm afraid

```
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

0 static files copied to '/data/static', 95 unmodified.
[2020-03-03 15:11:34 +0000] [17] [INFO] Starting gunicorn 20.0.4
[2020-03-03 15:11:34 +0000] [17] [INFO] Listening at: http://0.0.0.0:8000 (17)
[2020-03-03 15:11:34 +0000] [17] [INFO] Using worker: sync
[2020-03-03 15:11:34 +0000] [20] [INFO] Booting worker with pid: 20
[2020-03-03 15:11:34 +0000] [21] [INFO] Booting worker with pid: 21
[2020-03-03 15:11:34 +0000] [22] [INFO] Booting worker with pid: 22
[2020-03-03 15:11:34 +0000] [23] [INFO] Booting worker with pid: 23
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.
```

Unless the environment variable is required? But that's not mentioned anywhere... Like I said I followed the steps described in the documentation.

> Have you ever signed up?

I am trying to but unable to (as explained above). I click Sign Up, enter my new details, the page refreshes. Can't login using those details.

**Comment by winkidney** [comment]
When I use Firefox, when I use Chrome, the problem.

Ref from discord:
```
And sometimes Tt worked for me on Firefox when I logged in twice in a row
and now it works on Chrome too when I log in twice in a row
```

**Comment by winkidney** [comment]
@MaciekBaron The issue has been fixed now, please build a new version of Pinry and enjoy！

Ref：https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools

**Comment by winkidney** [comment]
Feel free to reopen this issue if you have any further problem.
