### ISSUE TITLE
Initial form state causes errors (null values)

### ISSUE THREAD

**Issue by MaciekBaron** [pinry/pinry#183]
The latest version of the build seems unstable - creating pins only works sometimes.

Sometimes the server returns a 400 error `{"private":["This field may not be null."]}`. Sometimes it seems to return a 200 but the pin does not get created. It seems to work if you toggle the privacy checkbox on and off, because I'm guessing it sets the value to not null but either true or false.

Payload sent: `{"referer":null,"description":null,"tags":[],"private":null,"image_by_id":7}`

Creation of boards also seems buggy, sometimes it works, sometimes it doesn't.

Tested on both Chrome and Firefox.

I think the initial form values need to be set properly so they're not null went sent to the server.

**Comment by winkidney** [comment]
@MaciekBaron fixed in latest version https://github.com/pinry/pinry/commit/144c816be3fb5a97e4b871668a4730c7b70bff71
Have a try to build new version and refresh your browser, (crtl + f5 and clean cache in chrome-terminal)

**Comment by winkidney** [comment]
Will be closed if no further replay.
Feel free to reopen it if you have any issue.
