### ISSUE TITLE
Can not add a new tag when I create a new pin.

### ISSUE THREAD

**Issue by Rousong** [pinry/pinry#187]
I am using the dev-env,
when I create a new pin and add some tags,
the tag dosen't appear below the pin.
![20200415122444](https://user-images.githubusercontent.com/29408759/79295680-3bf1d780-7f14-11ea-818b-57ef07671d30.png)
![20200415122453](https://user-images.githubusercontent.com/29408759/79295687-3dbb9b00-7f14-11ea-8a16-70fbdbe361ad.png)

**Comment by winkidney** [comment]
It's a bug/feature for buefy's tag-input, you have to add a comma(",") after your tag so that it could be add to the list.
