### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by markclanfalconer** [pinry/pinry#189]
Hi,

I am running the latest codebase as of 20/04/2020 in a docker container. Tags are not working at all. When I add or edit a pin and type in a tag:

![EditPin](https://user-images.githubusercontent.com/48368184/80145663-73adee80-85a8-11ea-840a-724e7fe8cf85.png)

After I click 'Save Changes' no tag is set:

![TagNotSet](https://user-images.githubusercontent.com/48368184/80145753-96d89e00-85a8-11ea-9c94-7886c6d857c6.png)

I would be happy to investigate error logs if you can tell me where to look.

Thanks and regards,

Mark

**Comment by markclanfalconer** [comment]
I have tried using both Firefox and Chrome browsers. I have tried disabling all my Firefox extensions. I have tried using the 'interact' feature of the API documentation. The weird thing is that the tags are simply not sent:

![image](https://user-images.githubusercontent.com/48368184/80159475-fc398880-85c2-11ea-83e7-4bd198f8d6d3.png)

**Comment by markclanfalconer** [comment]
I see, the tags in the API need to be in quotes:

![image](https://user-images.githubusercontent.com/48368184/80163225-6525fe00-85cd-11ea-8ddf-2bc5dfe60305.png)

I still cannot get tags to work from the 'Edit Pin' page though

**Comment by markclanfalconer** [comment]
... and on the 'Edit Pin' Tag input field you need to type a new Tag name then hit 'Enter' before you click Submit (I was trying 'Tab'). Needing a keypress is not at all obvious, but it works if you know.

**Comment by markclanfalconer** [comment]
Thank you for Pinry, it is exactly what I was looking for.

**Comment by winkidney** [comment]
Feel sorry for the bad user-experience caused by this feature/bug.
More detail about the reason we don't support add a single tag directly is here: https://github.com/pinry/pinry/issues/187

It's caused by our front-end framework's feature and we now have no plan to fix it by ourselves currently.
