### ISSUE TITLE
Is there still an admin site?

### ISSUE THREAD

**Issue by markclanfalconer** [pinry/pinry#190]
I am running the latest codebase as of 20/04/2020 in a docker containe.

According to https://docs.getpinry.com/passwords/ I should be able to navigate to an admin site.

![image](https://user-images.githubusercontent.com/48368184/80184117-ebf4ce00-8601-11ea-92dd-03f811c678a0.png)

![image](https://user-images.githubusercontent.com/48368184/80184170-fd3dda80-8601-11ea-857a-c46397edfd27.png)

**Comment by Rousong** [comment]
Hello markclanfalconer
You should run it on 8000 port.
The backend server Django  runs on port 8000

**Comment by Rousong** [comment]
localhost:8000 is default address.

**Comment by markclanfalconer** [comment]
2020/04/24 00:05:53 [error] 12#12: *607 open() "/data/static/rest_framework/css/bootstrap.min.css.map" failed (2: No such file or directory), client: 192.168.0.10, server: _, request: "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1", host: "192.168.0.24:8080"
2020/04/24 00:12:58 [error] 12#12: *608 open() "/data/static/rest_framework/css/bootstrap-theme.min.css.map" failed (2: No such file or directory), client: 192.168.0.10, server: _, request: "GET /static/rest_framework/css/bootstrap-theme.min.css.map HTTP/1.1", host: "192.168.0.24:8080"
2020/04/24 07:01:34 [error] 15#15: *716 open() "/pinry/pinry-spa/dist/admin" failed (2: No such file or directory), client: 192.168.0.10, server: _, request: "GET /admin HTTP/1.1", host: "192.168.0.24:8080"
2020/04/24 07:01:34 [error] 15#15: *716 open() "/pinry/pinry-spa/dist/favicon.ico" failed (2: No such file or directory), client: 192.168.0.10, server: _, request: "GET /favicon.ico HTTP/1.1", host: "192.168.0.24:8080"
2020/04/24 07:01:40 [error] 15#15: *714 "/pinry/pinry-spa/dist/admin/index.html" is not found (2: No such file or directory), client: 192.168.0.10, server: _, request: "GET /admin/ HTTP/1.1", host: "192.168.0.24:8080"

**Comment by markclanfalconer** [comment]
Thanks @Rousong

**Comment by markclanfalconer** [comment]
I restart my docker container mapping port 8000 - 80 instead of 8080 - 80. I get the same problem

![image](https://user-images.githubusercontent.com/48368184/80185156-c668c400-8603-11ea-9f8c-823cb31ec948.png)

I followed the instructions at https://docs.getpinry.com/install-with-docker/

Do I need to change my docker config to expose port 8000 and map it?

**Comment by Rousong** [comment]
try:
ports:
      - "127.0.0.1:8000:8000"

**Comment by winkidney** [comment]
Hi, Pinry still has an admin site but not exported to docker-instance.
You could add 
```
location /admin {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://localhost:8000;
        break;
    }
```
to file `docker/nginx/sites-enabled/default` then build your own docker image, the admin panel will be available in docker's nginx.

You chould also try to export django server directly via add config to docker just like @Rousong said:
```
ports:
- "127.0.0.1:8000:8000"
```

**Comment by winkidney** [comment]
The feature will be add at next patch and thanks for your feedback

**Comment by winkidney** [comment]
![image](https://user-images.githubusercontent.com/4109722/80193607-b379e200-864b-11ea-9afa-a6e92db637e7.png)
done, please update to latest version and rebuild the docker.

**Comment by winkidney** [comment]
Will be  closed, feel free to reopen it if you have any further problem.

**Comment by markclanfalconer** [comment]
Confirm pull add the admin page. Thanks!

![image](https://user-images.githubusercontent.com/48368184/80211041-cd57fc80-862c-11ea-85e3-b2efa29aabae.png)
