### ISSUE TITLE
sdist is broken

### ISSUE THREAD

**Issue by jayvdb** [pinry/pinry#193]
```py
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    long_description=read('README.rst'),
  File "setup.py", line 7, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by winkidney** [comment]
Hi jayvdb, 
Sorry for that but it seems that Pinry has no file named `setup.py` and this project has no setup file or and piny has not been distributed on pypi.

Feel free to reopen this issue if you have more information about this issue.

**Comment by jayvdb** [comment]
https://pypi.org/project/pinry/ - it has been distributed on PyPI

**Comment by winkidney** [comment]
Feel sorry for my mistake, that release may be old release which has been deprecated.
Pinry now use Pipenv as dependency management tool.
Please use the latest release on github instead of which on pypi.
