### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by lonix1** [pinry/pinry#196]
Is there an official docker image?

**Comment by winkidney** [comment]
Short answer: No
Long answer: Yes
We have no official docker image currently, but you could clone the project and set docker-auto-build on docker-hub.

I have my own version of docker image: https://hub.docker.com/repository/docker/kidneywin/pinry

It use the docker-fork in my owner account "github.com/winkidney/pinry".

I have updated it to latest version, you could pull it once the build done.

**Comment by lonix1** [comment]
Thanks for the tips.

It is a pity though, that there isn't an "official" image.

I tried to set up from source, and just gave up after a while. I guess I'm spoiled by docker's simplicity. 😆 

Has there been no interest? For such a popular project I was surprised at that.

**Comment by winkidney** [comment]
I may try to setup an account for Pinry.

**Comment by lonix1** [comment]
That would be great. Let me know when, and I'll beta test it for you.

**Comment by winkidney** [comment]
Feel sorry but I found that I don't have permission to build docker automatically in this organization after I tried some simple way(except I build it on my owner server and push it to dockerhub).
@overshard  may help, please contact me via email if you'd like to add docker-auto-build. I have registered an account named getpinry(pinry has been registered by other people)

**Comment by overshard** [comment]
@winkidney I've added you as an admin which I believe should give you the access you need? Let me know if you still don't have it though.

**Comment by winkidney** [comment]
@overshard It's awesome! I am able to  set the  secret username and password now. Thanks!

**Comment by winkidney** [comment]
@lonix1 it's our official docker image now: https://hub.docker.com/repository/docker/getpinry/pinry

**Comment by winkidney** [comment]
Feel free to reopen this issue if you have any further problem~

**Comment by lonix1** [comment]
Bravo!

May I suggest two things?

1. To update the [docs page](https://docs.getpinry.com/install-with-docker/) with a link to the official image. Users no longer need to build it themselves, they can just use the official one! This should encourage more users to try the app.

2. The docker hub name [`pinry/pinry`](https://hub.docker.com/r/pinry/pinry) is unofficial and hasn't been used in two years. I think we can claim it back.

Docker has [a procedure](https://success.docker.com/article/how-do-i-claim-an-inactive-docker-id) to reclaim the name. Whoever owns the account can open a ticket for this.

In fact [their rules](https://www.docker.com/legal/docker-terms-service) are on our side:
> **4.3 Username Squatting.** You may not and may not allow any third party to engage in username squatting. Accounts that are inactive for more than six months may be terminated at our discretion and without further notice. We take into account several factors when determining what conduct is considered to be username squatting including, without limitation:

**Comment by winkidney** [comment]
@lonix1 Thanks for your suggestions, I will add the image link to our official doc right now.
I'll have a try to claim back (or just contact the account owner) once I have time.

**Comment by lonix1** [comment]
@winkidney Don't bother trying that I already did - there is no contact information for that account (that I could find).

I think it qualifies as "name squatting".

I tried to lodge a ticket to get the process going (using that link above), but apparently only the account owner can do that (i.e. "getpinry").
