### ISSUE TITLE
I'd like to create a 404 page and remove the '/#/' from URL

### ISSUE THREAD

**Issue by Rousong** [pinry/pinry#197]
Is this nessasary for Pinry project?

**Comment by winkidney** [comment]
It's necessary but we haven't done that.
Pull request is very welcome : )

**Comment by winkidney** [comment]
If you want to do '/#/' removing and 404 page, please turn them into two separated PR.

**Comment by winkidney** [comment]
related PR: https://github.com/pinry/pinry/pull/199

**Comment by winkidney** [comment]
You commits is included in https://github.com/pinry/pinry/pull/224 and been updated by me.
Thanks for you work again and your PR has been closed since these commits is included.
