### ISSUE TITLE
How to set batch upload

### ISSUE THREAD

**Issue by fdxx** [pinry/pinry#201]
Hello, I have successfully installed, but I can only upload one image at a time. How to set batch upload, Thank you

**Comment by winkidney** [comment]
Currently we have no easy way to upload multiple image at a time.
You could just upload and then create pin with is by calling Pinry's API.
The api doc is here: http://your-domain/api/v2/
Personally, I wrote a python script to import my collections on other site.

**Comment by fdxx** [comment]
Thanks

**Comment by Rousong** [comment]
@winkidney Would you mind telling me how to write this script? Thank you!!

**Comment by zhiboz** [comment]
> Currently we have no easy way to upload multiple images at a time.
> You could just upload and then create pin with it by calling Pinry's API.
> The api doc is here: http://your-domain/api/v2/
> Personally, I wrote a python script to import my collections on other site.

@winkidney could you share your python script batching loading images into individual Pins? thanks!

**Comment by winkidney** [comment]
@zhiboz  It's ok, will be done later.

**Comment by winkidney** [comment]
@zhiboz just a ref, you have to modify it in your own way: https://github.com/winkidney/PickTrue/blob/feature/import-to-pinry/src/picktrue/pinry/uploader.py
