### ISSUE TITLE
Pinry doesn't work with PUBLIC set to False

### ISSUE THREAD

**Issue by TeMPOraL** [pinry/pinry#203]
Almost every request, including the API call necessary to log the user in, 500s with the following error:

```
NoReverseMatch at /api/v2/profile/users/

Reverse for 'private' not found. 'private' is not a valid view function or pattern name.
```

Done on fresh checkout of the master branch from ~1 hour ago, deployed via docker according to the documentation.

**Comment by winkidney** [comment]
Thanks for your feedback, will be tested once I have time.

**Comment by winkidney** [comment]
Have ever tried to register or login?

**Comment by winkidney** [comment]
Add workaround for it, you could register or login at non-public mode now.
Please checkout the latest master branch (or just wait for the docker-build to finish).

**Comment by TeMPOraL** [comment]
> Have ever tried to register or login?

Yes, in my initial attempt I switched to `PUBLIC=False` only after creating the first account. After doing that, I could no longer log in or register a new account.

Related, it seems to me that without this feature, private boards/pins don't work either, as they get shown on the front page even if logged out.

Thanks for the workaround, I'll test it.

**Comment by winkidney** [comment]
Private pin/board works for me on my own instance pin.37soloist.com. After I logout, the private pins and boards were hidden in the page.

If you want to set private, please make the pin this status:
![image](https://user-images.githubusercontent.com/4109722/83473579-83c8c000-a4bc-11ea-888a-530382c50949.png)
