### ISSUE TITLE
[Feature Request] Docker image versioning

### ISSUE THREAD

**Issue by lonix1** [pinry/pinry#204]
The official docker image only has the `latest` tag. This creates a problem if we want to "pin" (😆) the app to a specific version.

That is best practice, because it avoids deployment problems. When we pin to a version, we can test it before we deploy it, and know that it works. If we use `latest` then it will always pull the latest version, and possible break a deployment that we know should be working.

So could we consider also having a version? For example:
- `getpinry/pinry:latest`
- `getpinry/pinry:2.0.1`

**Comment by winkidney** [comment]
Nice to have.

**Comment by winkidney** [comment]
Our versioning build has been setup, this is the first version of with version tag:

https://hub.docker.com/repository/registry-1.docker.io/getpinry/pinry/builds/7d2a7ed6-7f39-49af-89ab-46541739f610

Once the build done, the version should be available.

This issue will be closed, feel free to reopen it if you have any further problem.

**Comment by lonix1** [comment]
thanks!
