### ISSUE TITLE
Non-ASCII tags not fully supported

### ISSUE THREAD

**Issue by IanGoo** [pinry/pinry#231]
I tried tags in Chinese, they can be attached. But there are two issues: 

1. These tags will not appear in recently used tag list when pining new images.
2. They cannot be searched.

**Comment by winkidney** [comment]
We have a simple cache for tags, so your may access them after about 5minutes.

After that, you could search from them.

Currently we have no "recently used tag list", we will  appreciate that you could make a Pull Request for it.

**Comment by winkidney** [comment]
No further reply, closed
Feel free to reopen it if you have further problem.
