### ISSUE TITLE
[Feature] Make all Pins private

### ISSUE THREAD

**Issue by Avalarion** [pinry/pinry#232]
Hey there,

I am planning photoshootings with pinry. Sometimes I invite someone to pinry to watch over a board with me and create a new board adding my pins of board one to a new board.

Everything is fine, but I also add erotic and nude pictures to my boards and when there is someone not feeling familiar with this or not in the right age this should not be shown. So I would love to have the possibility to say:

- Don't show this pin to everyone
- Don't show this board to everyone
- Only show Pin on board

Have a nice day,

Bastian

**Comment by winkidney** [comment]
Hi, the board and the pin has "private" option now. Have you ever checked it out?
If you still have some problem on the feature (e.g: it doesn't work as you expected), feel free to contact me again.

**Comment by Avalarion** [comment]
I have a board and pins that do not have the flag "visible to everyone" but the pictures are shown to all accounts on this setup =/. So I guess this is not working or the wording is wrong? Or are there any user rights that I clicked wrong in the admin area?

**Comment by winkidney** [comment]
Public pins in a private board  will be visible for others.
So if you want to keep all of them invisible, you should set all pins invisible.

![image](https://user-images.githubusercontent.com/4109722/98201781-70d68200-1f6b-11eb-8e2c-7ff80efdd7ec.png)

Check the box so that the board will be invisible.

**Comment by Avalarion** [comment]
Oh. May I suggest to change this text? I have no clue right now to what, but for me everything would have been "visible to everyone" when checking the box. Now after I checked the box I know what this is doing^^.

**Comment by winkidney** [comment]
Maybe the text confuses us.
What's your opinion on how we change the text to make it better to understand?

**Comment by es9o** [comment]
In my opinion, the text should stay the same whether or not the box is checked.

If by default the box says "visible to everyone", then it should be checked if the pin/board is actually visible to everyone. If a pin/board is private, the box should still say "visible to everyone" but remain unchecked to indicate that the option to make it visible to everyone has not been selected.

I made the same mistake @Avalarion made when first setting up my pins/boards.

**Comment by winkidney** [comment]
![image](https://user-images.githubusercontent.com/4109722/99950545-a080e900-2db7-11eb-840d-aaa1de9e33e6.png)
coming soon!

**Comment by winkidney** [comment]
@Avalarion @es9o already done, please use the latest docker image once the automatic build done.
