### ISSUE TITLE
[Feature] Share private Boards to other Users

### ISSUE THREAD

**Issue by Avalarion** [pinry/pinry#234]
I requested a feature with private boards, additionally to that request it would be awesome to have the possibility to Allow other users of my pinry installation to view my boards and all pins on them.

**Comment by winkidney** [comment]
This is duplicated with another issue: https://github.com/pinry/pinry/issues/233

If a board has password, it should be private.

Both the features could be merged into one feature.

**Comment by winkidney** [comment]
closed since duplicate.
