### ISSUE TITLE
apache2 config example

### ISSUE THREAD

**Issue by GPConnect** [pinry/pinry#241]
Hello, 
any apache2 reverse proxy config to use with pinry docker ? 
my config file may be missing something ! can't sign in since i added ssl !
thanks

**Comment by winkidney** [comment]
It seems that SSL it not related to how you connect to pinry.
Any code for your config? Maybe I could help with that : )

**Comment by GPConnect** [comment]
i can not login only when using my apache reverse proxy to add ssl ! maybe i missed something in my config ! don't know thank for the help ! 
<img width="556" alt="Capture d’écran 2021-01-01 à 17 29 43" src="https://user-images.githubusercontent.com/25872687/103446565-624cd400-4c57-11eb-86a6-1988d611bb3e.png">
<img width="511" alt="Capture d’écran 2021-01-01 à 17 30 50" src="https://user-images.githubusercontent.com/25872687/103446566-6547c480-4c57-11eb-9bc5-2c1422ac9fac.png">

**Comment by GPConnect** [comment]
still no help :) 
none use pinry with apache ! no love for it ?
i guess i can not hit the api with my apache config ! 
i can see the example for nginx, so how to translate it to apache2 ?

**Comment by winkidney** [comment]
Feel sorry for missing this issue.

I have no experience on apache2 and I have no enough time to make apache2-environment, I will have a try in a week and try to give you an config example.
And, thanks for your patience.

BTW: would you like to give me your 403 response content in browser's network tab in dev-tools?

**Comment by GPConnect** [comment]
Moved to a vm running nginx !

**Comment by winkidney** [comment]
I have installed apache2 on ubuntu20 (version is 2.4.41) and made a sample config without SSL.

```
<VirtualHost *:80>
	DocumentRoot /home/winkidney/workspace/side-projects/pinry/pinry-spa/dist
    Alias /media /home/winkidney/workspace/side-projects/pinry/static/media
    <Directory  "/home/winkidney/workspace/side-projects/pinry/pinry-spa/dist">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
		Require all granted
    </Directory>
    

	<Directory "/home/winkidney/workspace/side-projects/pinry/static/media">
        Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Require all granted
    </Directory>

	ProxyPreserveHost On
	ProxyPass /api http://127.0.0.1:8000/api
    ProxyPass /admin http://127.0.0.1:8000/admin
	
    ServerAdmin localhost

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

It works well with my frontend files and media directory, I believe that you could use it to add your own SSL config.

Feel free to tell me if you have any further problem.

**Comment by winkidney** [comment]
Oh I haven't set X-Forward related, you could add it by your own.

**Comment by winkidney** [comment]
`FallbackResource /index.html` should also be add.

The complete example has been changed.

**Comment by pythonInRelay** [comment]
I recommend using NginxProxyManager and not trying to mess around with specific config files. There's really no reason to resort to old tactics when you can use a simple plugin or container to do the work of reverse proxying any services you have running safely and securely.
