### ISSUE TITLE
close window automatically after creating pin from plugin

### ISSUE THREAD

**Issue by slynn1324** [pinry/pinry#246]
I'm pretty sure a `window.close();` here works.  I couldn't test extensively, but I hacked it into the Docker image and it seems to work fine... 

https://github.com/pinry/pinry/blob/bd4c0e7f618a8e7cbb5406d7f31b949f318016ac/pinry-spa/src/views/PinCreate.vue#L43

**Comment by winkidney** [comment]
Pull Request is very welcome!
