### ISSUE TITLE
routes: /pins and /boards break on reload

### ISSUE THREAD

**Issue by dunn** [pinry/pinry#249]
I assume this has something to do with their being part of Vue rather than the Django application, but the routes defined here: https://github.com/pinry/pinry/blob/5e0c9ee79a70c4997810c6e6b51a460db4fe4fa0/pinry-spa/src/router/index.js

don't work outside of a browser context that begins at the root `/`.  (I.e., if you start at the home page you can navigate to `/pins` and `/boards` routes, but if you try to navigate to them directly, or reload the page, you get a 404.

**Comment by winkidney** [comment]
Will be verified once I have time, thanks.

**Comment by winkidney** [comment]
It seems that it works well in my Pinry instance at pin.37soloist.com.
Refreshing will not cause 404.

We have no globbal "boards" and "pins", we have only pins and boards for specified user.

PR is welcome.

**Comment by dunn** [comment]
oh interesting, i'll have to look at my configuration

**Comment by dunn** [comment]
figured it out, i had my nginx configured to route those requests to django, rather than to `/index.html` so they weren't being caught by vue
