### ISSUE TITLE
Unable to log in to new install

### ISSUE THREAD

**Issue by kdmiller45** [pinry/pinry#254]
Installed on Ubuntu 20.04
Dell R-610, 96Gig Ram, 2Tb storage

I installed system and instruction say change ALLOW_NEW_REGISTRATIONS = True it was already set, but when I try to create account it says not allowed
the path was pinty/pinry/settings/local_settings.py
I have rebooted system with same issue

**Comment by winkidney** [comment]
Hi，What's the return code of your register-request? any more information for your install?

**Comment by kdmiller45** [comment]
I uninstalled and reinstalled the application it did come  up ok this is still in basic development it looks l like, but has potential, any plans to have an email system for password recovery and notification to admin of new user registration

**Comment by kdmiller45** [comment]
Also, I just tried to pin a URL and all it did was spin at me in the large square upper Left. a NOTE: when you build from the source it did not for me create/populate the Data folder I had to perform a pull from getpinry/pinry to do that

**Comment by winkidney** [comment]
Thanks for you feedback.


Yes, admin and email system is required to create a public PinSystem, maybe a user-management should be built.
-----------------

Data folder will be create if you use Dockerfile.autobuild to build the docker, if you use the development dockerfile, it will not be done.

**Comment by MWP** [comment]
Frustrated....  the pinry installation docco is terrible.

Installing the docker container is easy enough, but then what?
The docs say to set ALLOW_NEW_REGISTRATIONS=True in local_settings.py. But where is this file? How do i access / edit it?
Same goes with the password change information.

The docs website could really do with more command line examples for both bare-metal and docker containers.
A little bit more docco would go a long way.
... ive come across a few other forums/discussions of people with similar frustrations.

**Comment by winkidney** [comment]
No further update ,closed.
