### ISSUE TITLE
Remove Gravatar, plus many other features

### ISSUE THREAD

**Issue by pythonInRelay** [pinry/pinry#264]
Just curious if someone knows how to do this easily, aka what .css files and so on I'd need to edit for each thing.

- I'd like to remove Gravatar because it requires an account and no one uses it and in its place set a static 50x50px image
- Triple the size of thumbnails/image pins on boards
- Change the background color of the entire board to something much darker or some sort of pattern
- Increase the size of images/pins that have been clicked on to fill as much of the screen as possible (by height) but not have them scroll
- Allow a user to click on an image to view the full size immediately in new window
- Outright remove the Gravatar/"Pinned by user-x" bottom footer on each pin to save space
- Fully remove the Sign Up button so people can't upload stuff to my own server (instead of just disabling registration because currently disabling registration does not provoke any kind of "Registration disabled" message)

Are any of these features planned? It would be nice to have most of them in a user menu.

I have tried myself to find where the corresponding values and variables are for these functions but I cannot find them. I've been able to disable registrations via the settings.py file but not change thumbnail sizes or find where the background color/style setting is. 

Any info would be appreciated. If someone can tell me how to change/set these features I'm happy to share/commit my own changes. Just having a hard time figuring out where everything is located.

**Comment by winkidney** [comment]
+ Gravatar: Remove is not possible now
+ Triple the size: Not really possible, you could change it in local_settings.py bit it will work only for backend. The size in frontend is defined by css. not the settings.
+ Background color could be set now, it is defined by frontend, you can just change the css.
+ Email to open: Not possible now.
+ Remove "pinned by user", frontend should be changed.
+ Sign Up: will be fixed with error message.

**Comment by winkidney** [comment]
```
# thumbnail size control
IMAGE_SIZES = {
    'thumbnail': {'size': [240, 0]},
    'standard': {'size': [600, 0]},
    'square': {'crop': True, 'size': [125, 125]},
}
```

**Comment by pythonInRelay** [comment]
> 
> 
> ```
> # thumbnail size control
> IMAGE_SIZES = {
>     'thumbnail': {'size': [240, 0]},
>     'standard': {'size': [600, 0]},
>     'square': {'crop': True, 'size': [125, 125]},
> }
> ```

This doesn't work sadly. It changes absolutely nothing on the main page :(

**Comment by winkidney** [comment]
it's here:
https://github.com/pinry/pinry/blob/master/pinry-spa/src/components/Pins.vue
`grid-item { width: $pin-preview-width; }`

You may face many other problem for example changes on responsive-grid-system should be made.

**Comment by pythonInRelay** [comment]
Thanks, I tried this and it works fine and thankfully many of the other settings are in there. It'd be great to have some of these variables as user-defined settings on the accounts page. In particular pin size, gutter/footer size and the possibility to remove the author and source from the board's page.

I'm going to try to hack together my own front-end .css but I have kind of limited experience with Vue.

**Comment by winkidney** [comment]
> 
> 
> Thanks, I tried this and it works fine and thankfully many of the other settings are in there. It'd be great to have some of these variables as user-defined settings on the accounts page. In particular pin size, gutter/footer size and the possibility to remove the author and source from the board's page.
> 
> I'm going to try to hack together my own front-end .css but I have kind of limited experience with Vue.

It would be great to have ability to customize those parameters.
I have no time to do things like that currently, Pull Request is very welcome.

**Comment by pythonInRelay** [comment]
I wasn't able to do this reliably in Vue.js myself due to how the application is coded.

I see that you closed the Issue. Could you please consider adding at least the two following features as a priority:

* Possibility to upload own avatar on user page (not use Gravatar), it should be very easy to put together as most of the code is already there for uploading pins.

* Possibility to increase the size of pins by 25/50%

The rest of the features are easy enough to change but these two should really be considered from a design and usability standpoint. If you really do not have time, maybe consider keeping the Issue open so someone else can stumble across it.

**Comment by winkidney** [comment]
@pythonInRelay 

Both of the freature should be standalone feature request. 
The first one could be done easily while the second one it not easy (because it is a design descion not a coding problem). I personally don't agree to increase the size of pins by 25%/50%.

For the first one, I will be a global standalone issue.

For the second one, you should change both the grid system related arguments at frontend and thumbmail arguments at backend. I may provide a PR to show how should we change it.

**Comment by winkidney** [comment]
Gravatar related : https://github.com/pinry/pinry/issues/270
