### ISSUE TITLE
Troubleshooting slow load times / docker

### ISSUE THREAD

**Issue by Billiam** [pinry/pinry#266]
I'm having some trouble with Pinry load times, with a couple of api requests (`api/v2/profile/users` and `api/v2/pins`) taking 10-20 seconds for a small board without a lot of content.

What can I change to improve this? I haven't seen the issue come up elsewhere so I assume it's an issue with my installation.

**Comment by winkidney** [comment]
Would you like to provide your requests flow or any debug info for the request loading?

We need request and response details(either text or screenshot is ok) to figure out the issue.

**Comment by Billiam** [comment]
Sure. Here's what it typically looks like, though often closer to 20 seconds.

![pinry](https://user-images.githubusercontent.com/242008/113496249-63dba180-94bd-11eb-83b5-ec9caa5e7170.jpg)

Subsequent reloads will mostly, but not always, return much faster (<200ms), even without any browser caching.

**Comment by winkidney** [comment]
Thanks for your feedback.
How many pins and users you own on your Pinry instance?
What's your system configuration (for example cpu, memory, harddisk)?
When it is slow, how is the system load looks like?

**Comment by Billiam** [comment]
> How many pins and users you own on your Pinry instance?

2 users,  less than 50 total pins.

> What's your system configuration (for example cpu, memory, harddisk)?

Distro: Ubuntu 16 LTS
CPU: I3-4130
Mem: 4gb ddr3 PC3-12800. About 2gb free
Disk: 2x 4tb hdd in a btrfs array

> When it is slow, how is the system load looks like?

Low CPU before the request (<3% on any of 4 cores). During the request, one pinry process goes as high as 6 or 7%, so not much going on.

**Comment by winkidney** [comment]
> 
> 
> > How many pins and users you own on your Pinry instance?
> 
> 2 users, less than 50 total pins.
> 
> > What's your system configuration (for example cpu, memory, harddisk)?
> 
> Distro: Ubuntu 16 LTS
> CPU: I3-4130
> Mem: 4gb ddr3 PC3-12800. About 2gb free
> Disk: 2x 4tb hdd in a btrfs array
> 
> > When it is slow, how is the system load looks like?
> 
> Low CPU before the request (<3% on any of 4 cores). During the request, one pinry process goes as high as 6 or 7%, so not much going on.

Feel sorry for that I have no idea about how it works slow like that currently.
