### ISSUE TITLE
On some sites, when using bookmarklet or Lapo's browser addon, list of images appears behind content

### ISSUE THREAD

**Issue by PaperbackSpine** [pinry/pinry#273]
When I activate the bookmarklet, or when I use lapo's firefox addon, the list of images I need to pick from is hidden behind the content.

It only happens on some websites, I suppose because some CSS doesn't play nicely with the bookmarklet's own CSS.

Example URL where this happens.: https://ablackbrick.tumblr.com/post/641203544675975168/the-death-of-the-suzerain

Firefox, Win 10.

**Comment by PaperbackSpine** [comment]
Another example, if you enlarge one of the images first by clicking on it, you can only select which one you want to pin by clicking the bookmarklet, and then the dark border around the enlarged image: https://glyptolite.tumblr.com/post/648931856639787008/asemic-art-by-cc33

**Comment by winkidney** [comment]
It may be a issue caused by  z-index.
I will try to figure it out once I have time.

Thanks for your feedback.

**Comment by lapo-luchini** [comment]
Same here, will take a look soon.

**Comment by lapo-luchini** [comment]
Works for me, but I have some unmerged local changes, including a huge zIndex increase.
Will create PRs.
