### ISSUE TITLE
Translate Pinry

### ISSUE THREAD

**Issue by ConsultorML** [pinry/pinry#288]
Hi, is possible to translate Pinry? I want to use it in spanish. I can help translating the strings. How can we do it?
Thanks!

**Comment by winkidney** [comment]
i18n is not possible now, we need a i18n basic frame, we need two tool to make it possible.

+ Add i18n support in frontend
+ Enable i18n support in backend

But I have no enough free time to do that, PR is very welcome!

**Comment by ConsultorML** [comment]
Thanks for the response. Unfortunately I don't know programming, but if someone can and want to do it, I can help translating. 
Great software btw. Regards!

**Comment by dextor19** [comment]
> Thanks for the response. Unfortunately I don't know programming, but if someone can and want to do it, I can help translating. Great software btw. Regards!

@ConsultorML I have added a translation mechanism for Pinry, probably have a chat with winkidney about making spanish translations for Pinry.

**Comment by cleaverm** [comment]
@dextor19 nice work making it translateable!

I'd suggest (mostly to winkidney I suppose) integrating with a translation platform, it helps with context when someone is translating (think screenshots or hint text), and it can show which languages are missing phrases, as well as provide a platform for discussing translations. The repo here could just say "go here to help with translations" and keep the rest of the issues focused on the app itself.

Something like [crowdin](https://crowdin.com/pricing) or [Lokalise](https://lokalise.com/solutions/alternatives/crowdin-alternative) are free for open source projects. I have no experience with either of them myself though (just used a similar platform for a commercial app and appreciate the benefits it brought).

They usually consume/output the json files that dextor19 already introduced (i.e. that was a necessary step either way). I don't know at what point it makes sense to introduce another tool though... it's not like there are 100s of PRs a week waiting for review. It's worth considering though, and doing it for the first "new" language might be as good a time as any and save time later.

**Comment by winkidney** [comment]
I would have a try to translate Pinry to Chinese first, after that I may give a friendly way to translate Pinry as other language. @cleaverm

**Comment by winkidney** [comment]
I've made a more user-friendly UI for language selection.

If you want to translate spnish, I'd like to have a real-time talk with you and we could make it done together.

![image](https://user-images.githubusercontent.com/4109722/164768335-a8aba855-0bf1-45cf-a013-b1dc8077d478.png)

**Comment by LilianBoulard** [comment]
Hey, I'm willing to help translate to French!

**Comment by winkidney** [comment]
Already done, should be closed
