### ISSUE TITLE
Official Apple M1 Arm Processor Support

### ISSUE THREAD

**Issue by dakotahp** [pinry/pinry#293]
I know some form of Arm support was [recently added](https://github.com/pinry/pinry/pull/248) but I think it only supports the Raspberry Pi platform. 

I got a warning (not a blocking error) when I ran this on the new M1 processor Macbook Pro. The app still launches so it isn't a huge deal but I thought I'd mention it so it can be addressed eventually.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
cbcba37ce4b23d998748d2ee1529f961483631e88cc022f9616f724bfb7a515c
```

Looking at the other PR, I don't actually see anything that adds Arm support in it but I'm not too familiar with this codebase so I could be missing something. Otherwise I'd make an attempt to add it.

Thanks for the cool app!

**Comment by winkidney** [comment]
https://github.com/pinry/pinry/pull/248
