### ISSUE TITLE
How to I recover my pins

### ISSUE THREAD

**Issue by jcm4atx** [pinry/pinry#294]
I'm running the Docker image. I'm not 100% certain what I did. All of my pins vanished. The /static directory is still intact and my pins appear to be there. Is there a way to recover this?

**Comment by jcm4atx** [comment]
I killed off the container and restarted. I even rebooted my server. I was hoping there'd be some way to make it rescan my /static directory.

**Comment by winkidney** [comment]
Feel sorry about that, it seems that I have no idea for your case.
Pinry will never rescan static directory. I advice you to search the *.sqlite in your container or other place.

Good luck.
