### ISSUE TITLE
REST API authentication?

### ISSUE THREAD

**Issue by Flamekebab** [pinry/pinry#305]
I used to run a Pinry 1.x instance and I'm planning to pull the data from its files and put them into Pinry 2.x but I'm fairly new to Django.

I've found the documentation at /api/v2/docs/ but I've not managed to authenticate with the API properly. If PUBLIC is set to True then the API works just fine. I can also get the API to work within a browser (as in if I login to Pinry and then make an API call in a new tab or similar). I've also succeeded by logging in in a browser and then copying the resultant sessions cookie to my REST client.

However I can't seem to figure out how to authenticate properly in a REST client. As far as I can tell I can set the login details in the docs - where I have it set to basic auth. But that doesn't seem to stick - maybe it's not supposed to.

I'm thinking I should add

```
'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
    ]
```

to  base.py but I don't really want to start messing about with files inside the Docker container if there's actually an easier way that is obvious to everyone else.

What's the correct way to authenticate?

**Comment by winkidney** [comment]
Hi, API-Auth is not provided currently, you could just use this script to do pinry import(FYI):
 https://github.com/winkidney/PickTrue/blob/feature/import-to-pinry/src/picktrue/pinry/uploader.py

**Comment by Flamekebab** [comment]
Thanks for the quick reply - that's cool. As I'm new to this I wasn't sure whether it wasn't implemented yet or whether I was just failing to understand how to use it.

I'm not sure if I'll use that importer but it's definitely useful in teaching me how this is supposed to work. Thanks!

**Comment by winkidney** [comment]
Glad to see it helps.
It's an example for login(session cookie based) and API-call, sou you could write your own script to let your job done.

**Comment by winkidney** [comment]
Hi, I've updated token-based API support in master branch, you could enjoy it currently : ), the detail is here:
https://github.com/pinry/pinry/pull/323
