### ISSUE TITLE
Upload and api auth

### ISSUE THREAD

**Issue by mbelletti** [pinry/pinry#310]
Hi I'm trying to upload a set of images on my pinry running on docker using the script you advice in #305:

https://github.com/winkidney/PickTrue/blob/feature/import-to-pinry/src/picktrue/pinry/uploader.py

The problem is that I'm not able to autenticate. 
Calling /api/v2/profile/login/ return 403. 

Looking at https://github.com/pinry/pinry/blob/master/pinry-spa/src/components/api.js I'm sure I'm missing something.
But what?
From debug I got:

> Forbidden (Referer checking failed - no Referer.): /api/v2/profile/login/

I've tried to add my calling ip/domain to ALLOWED_HOSTS but doesn't work.

Thank you

**Comment by winkidney** [comment]
You may add referer to headers.
```
self.session.headers.update(
            {"Referer": "your-url-of-pinry-site"}
        )
```

ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

**Comment by mbelletti** [comment]
Awesome! I was trying but I had a typo. (-:
Thank you! It work like a charme.
