### ISSUE TITLE
Can't log out?

### ISSUE THREAD

**Issue by florihupf** [pinry/pinry#324]
Hi there,

I have an install working using Apache2. All is good, but the only thing is, once logged in I can't log out.  I press the Log Out button, but the site refreshes and shows me the log out button again.

Happy to dig in, if anyone has a pointer where to look.

Thank you!

**Comment by winkidney** [comment]
Please provide some information about your working version of Pinry and how it works with your apache2 server.
And, you'd better have a look at  cookies before you logout.

If you could provide a networking request history in browser console, we may tell what happend.

**Comment by florihupf** [comment]
Thanks for the pointers, I was looking a bit more and found 

```
> journalctl -u pinry
```

gives me:

```
Feb 23 22:07:49 vm-01-seafile python3[292810]: Internal Server Error: /api/v2/profile/login/
Feb 23 22:07:49 vm-01-seafile python3[292810]: Traceback (most recent call last):
Feb 23 22:07:49 vm-01-seafile python3[292810]:   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
Feb 23 22:07:49 vm-01-seafile python3[292810]:     return self.cursor.execute(sql, params)
Feb 23 22:07:49 vm-01-seafile python3[292810]:   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/sqlite3/base.py", line 383, in execute
Feb 23 22:07:49 vm-01-seafile python3[292810]:     return Database.Cursor.execute(self, query, params)
```

That said, I even tried making the db world r/w, but no dice.  Will look more.

**Comment by florihupf** [comment]
Ok, never mind.

I was missing:

```
  ProxyPass /api-auth http://127.0.0.1:8888/api-auth
```

From the apache config.  All good now.
