### ISSUE TITLE
django.db.utils.OperationalError: no such table: authtoken_token

### ISSUE THREAD

**Issue by keylogthis** [pinry/pinry#327]
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 5.10.0-0.bpo.11-amd64

I was running 2.1.5 in docker and I deleted the container and pulled the latest image and started it up with the same bind mount to /data and now it does nothing when I try to login with my existing user. It just stays at the login page, and gives this in the logs: [errors.log](https://github.com/pinry/pinry/files/8356523/pinry.log)

This is the docker run command which I used:

`docker run -d --name=pinry -p 80:80 -v /docker/pinry:/data getpinry/pinry`

So what is in my /data that is messing it up?

**Comment by winkidney** [comment]
go to docker and then run "make migrate"， it will work : )

**Comment by keylogthis** [comment]
I ran make migrate, no change, same problem.

[makemigrate.log](https://github.com/pinry/pinry/files/8358123/makemigrate.log)

**Comment by winkidney** [comment]
> I ran make migrate, no change, same problem.
> 
> [makemigrate.log](https://github.com/pinry/pinry/files/8358123/makemigrate.log)

The log shows that your migration doesn't work as expected.
I'll have a look at the error and then give you a reply.

**Comment by winkidney** [comment]
Sorry, no need to run `make migrate`, just run `./manage.py migrate`, it will works.
Please have a try and give me feedback, thanks.

**Comment by keylogthis** [comment]
That seems to end in an error too and doesn't solve the problem. Here is the output: [managemigrate.txt](https://github.com/pinry/pinry/files/8367046/managemigrate.txt)

**Comment by keylogthis** [comment]
Okay, so I saw that the error after running` ./manage.py migrate` was `ModuleNotFoundError: No module named 'django_extensions' ` So I did a `pip install django_extensions` then I ran `./manage.py migrate` again and it is now working. Thanks for helping.

**Comment by winkidney** [comment]
I'll make a script to docker so that we could migrate outside docker without any dependency issue.
And, thanks for your feedback again.
