### ISSUE TITLE
Performance issue with boards

### ISSUE THREAD

**Issue by kerenon** [pinry/pinry#339]
Pinry is literally what I was looking for, so I've decided to do some testing, to see if it works for what I intend to use it. I've installed the latest version (2.1.9) using docker, and created a single board with 300 images.
Loading the front page, works just fine. The page loads in an instant, and scrolling down, new images are loaded as needed. Opening the board directly behaves **very** differently. According to the browser developer tools, it seems to me that the page tries to load **all** of the 300 images at once, slowing the page down to a crawl. The outgoing network traffic from the server goes up like crazy, before it finally settles down. Other then the increase in bandwidth, the server does practically nothing. CPU usage is <10% with a lot of other processes running. Opening the same board on a Galaxy S20 Ultra sometimes needs so much time, that the "App not responding" question pops up. Tested with all current popular desktop and mobile browsers.

**Comment by winkidney** [comment]
Thanks for your feedback and I will have a look on it.

**Comment by winkidney** [comment]
Hi, I've figure it out.
It is just because we load all image once a time in "board view", it's not lazy load.

I'll have a test on it and fix it soon.

**Comment by winkidney** [comment]
PR created: https://github.com/pinry/pinry/pull/341

**Comment by winkidney** [comment]
Please pull the docker after a while, I've created new commits and building the docker images.

**Comment by winkidney** [comment]
> Thanks. Tried running the PR in docker, but it won't start:
> 
> ```
> pinry    | /pinry/docker/scripts/start.sh: line 17: make: command not found
> pinry    | [2022-05-04 13:54:47 +0000] [18] [INFO] Starting gunicorn 20.1.0
> pinry    | [2022-05-04 13:54:47 +0000] [18] [INFO] Listening at: http://0.0.0.0:8000 (18)
> pinry    | [2022-05-04 13:54:47 +0000] [18] [INFO] Using worker: sync
> pinry    | [2022-05-04 13:54:47 +0000] [20] [INFO] Booting worker with pid: 20
> pinry    | [2022-05-04 13:54:47 +0000] [20] [ERROR] Exception in worker process
> pinry    | Traceback (most recent call last):
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
> pinry    |   File "/root/.cache/pypoetry/virtualenvs/pinry-P62RBkeW-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
> pinry    |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
> pinry    |     return _bootstrap._gcd_import(name[level:], package, level)
> pinry    |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> pinry    |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> pinry    |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> pinry    |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> pinry    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
> pinry    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> pinry    |   File "/pinry/pinry/wsgi.py", line 1, in <module>
> pinry    |     from django.core.wsgi import get_wsgi_application
> pinry    | ModuleNotFoundError: No module named 'django'
> pinry    | [2022-05-04 13:54:47 +0000] [20] [INFO] Worker exiting (pid: 20)
> ```
> 
> I can test it on bare metal, but it's gonna take a few days.

New commits has been commited, you could use master branch directly now.

**Comment by winkidney** [comment]
the pre-built container version is 2.1.11

**Comment by kerenon** [comment]
2.1.11 works perfectly. Thank you.
