### ISSUE TITLE
Can't remove images from boards after 2.1.11 upgrade

### ISSUE THREAD

**Issue by kerenon** [pinry/pinry#342]
After upgrading to 2.1.11, the "remove image from board" button vanished, and I can't seem to find any other way to do this. Downgrading to 2.1.9 brings it back.
![image](https://user-images.githubusercontent.com/4417798/166976140-9e579e5b-9843-47f9-b1d1-4a0f44cfd6c2.png)
![image](https://user-images.githubusercontent.com/4417798/166976479-ae1f990b-f0df-4ccc-bf6e-48e5da0c738b.png)

**Comment by winkidney** [comment]
Wow, I will have a look on it and fix it

**Comment by winkidney** [comment]
will be updated to v2.1.12

**Comment by winkidney** [comment]
Images in Board could be removed in my local environment.
Where you test the function, could you please made screenshots for me? 
Thanks.

**Comment by kerenon** [comment]
Sorry, it seems clearing the cache/cookies wasn't enough. Just tried it again and now it suddenly works. Not sure what happened, I meticulously cleared everything. Even tried it from a different browser profile.

Sorry and thanks... again :)
