### ISSUE TITLE
Don't zoom small image  in “large preview”

### ISSUE THREAD

**Issue by kerenon** [pinry/pinry#343]
Is it possible to keep Pinry from zooming in to small images like crazy? A config option perhaps? Right now those images look rather "interesting" :)

![small_img](https://user-images.githubusercontent.com/4417798/167269927-8875bca4-9b71-493d-a11f-72f8d7be8402.png)

**Comment by winkidney** [comment]
Nice to have, I have no nice strategy for this situation.
The design should be re-considered once I have time.

**Comment by kerenon** [comment]
It seems the problem is back. For some reason it seems the merged modifications are simply ignored. I literally know nothing about Vue, and after hours of trying to understand how the resulting css is generated, I think this is where I throw in the towel. I'm sure it's not a big problem but poking around without understanding what I'm doing is just time wasted.

**Comment by winkidney** [comment]
Feel Sorry， will be corrected in a week.
Thanks for your comment again : ).
