### ISSUE TITLE
getpinry.com is down

### ISSUE THREAD

**Issue by mahmoud** [pinry/pinry#352]
https://docs.getpinry.com is up, but [the main site](https://getpinry.com) displays:

![Screenshot from 2022-07-09 13-55-43](https://user-images.githubusercontent.com/130193/178122403-1c086b2f-ffa0-4a1e-99ab-e029f4540d70.png)

Also, nice project! :)

**Comment by winkidney** [comment]
Thanks mahumoud! @overshard please have a check if you have time : )

**Comment by overshard** [comment]
Hey all,

I'll check into this as soon as I can and get it fixed. Thanks for letting me know!

**Comment by overshard** [comment]
This issue should be fixed! Please let me know if it persists.

**Comment by Brancliff** [comment]
It's down again
