### ISSUE TITLE
Randomize Pins

### ISSUE THREAD

**Issue by drunkenpeleg** [pinry/pinry#354]
Each time Pinry loads, all pins are presented ordered by age. I see specific ordering is mentioned in #151 - I'd be interested in random order on load. =)

**Comment by winkidney** [comment]
Nice to have.

**Comment by Piotr12** [comment]
@drunkenpeleg  is that not something you can achieve by modifying views.py to sort on '?' instead on '-id' in lines 26-27? (not a django novice even but that seems to do the trick for me(?))

**Comment by drunkenpeleg** [comment]
> @drunkenpeleg is that not something you can achieve by modifying views.py to sort on '?' instead on '-id' in lines 26-27?

Finally got around to this and it worked like a charm, thanks!
