### ISSUE TITLE
Pornography on the demo site

### ISSUE THREAD

**Issue by nickludlam** [pinry/pinry#364]
I wanted to check out the project after seeing it on https://alternativeto.net/ only to find the demo site https://pin.37soloist.com/ contains a lot of pornographic images uploaded by a user called alluded This isn't a good look!

**Comment by winkidney** [comment]
Thanks for your feedback.
Will be checked : )

**Comment by winkidney** [comment]
Already hide : ) and thank you again.

**Comment by ishults** [comment]
@winkidney It's back up again.

**Comment by winkidney** [comment]
> @winkidney It's back up again.

thanks, cleaned.
