### ISSUE TITLE
Security Reports

### ISSUE THREAD

**Issue by bAuh0lz** [pinry/pinry#368]
Please check the reports.

- https://huntr.dev/bounties/166c8b52-a3f6-47d5-97e8-84b16b2fc3fe/
- https://huntr.dev/bounties/0e8d0c9e-316f-456d-a996-adb3c5ba523e/

**Comment by winkidney** [comment]
Thanks，will be fixed once I have time

**Comment by Avatat** [comment]
@winkidney, could you share the reports with me, please? Maybe I could fix the issues.

**Comment by winkidney** [comment]
both two issue has been fixed via PR https://github.com/pinry/pinry/pull/388

Thanks for your help @Avatat and also thanks for reports of @bAuh0lz .
