### ISSUE TITLE
"Pin tags" overflow "pin info"

### ISSUE THREAD

**Issue by illustietor** [pinry/pinry#374]
Hello!
I have noticed that if too many tags are added to a pin, they get out of the pin's "box."
![overflow-01](https://github.com/pinry/pinry/assets/33377376/1b299d45-8756-4801-9907-addd6b6a1f46)

This can be solved by adding the "display: inline-block" property to the "pin-tag" class in CSS.
![overflow 2](https://github.com/pinry/pinry/assets/33377376/f78b58df-dd60-4995-b396-fa0193895df6)

**Comment by winkidney** [comment]
Already fixed in this commit https://github.com/pinry/pinry/commit/6019a271044ea5ca8262b72d0fce34a9e37901cf
