### ISSUE TITLE
Private Pin / Private Board

### ISSUE THREAD

**Issue by awikatchikaen** [pinry/pinry#52]
Hi, 

My "gallery" is public and share with family and friends, but there are some pin I don't want to share. For example, in this christmas period I want to pin some presents ideas and don't want my wife or kids see them.

It could be a checkbox on pin formulaire, or maybe a tag 'private' to add manually...

Thank you.

**Comment by winkidney** [comment]
@awikatchikaen @Friss Private Pin and Private Board works well in the latest version https://github.com/pinry/pinry/commit/b9ce43f985fb18896d5659c1b7c020df3d45db3b , please have a try and give us feedback if possible, thanks!
