### ISSUE TITLE
Vimeo and Youtube pinning support

### ISSUE THREAD

**Issue by overshard** [pinry/pinry#6]
The core social video sites for now since they both have easy embeddables. Need to grab a "screenshot" of the video, can be done via the API I think, to put as the pin thumbnail.

**Comment by overshard** [comment]
I'm not sure how much interest we have in pinning videos at this point in time, it's basically the same as a "Website URL" pin. I'm closing this.

**Comment by lapo-luchini** [comment]
OTOH I seldom would like to pin "short mp4", which is such a better* format than "gif" ever was and is finally starting to replace it…
*: as in full 24bit colors occuping 1/10-1/50 than a shiffy 256-colors animation.
