### ISSUE TITLE
Trouble getting running

### ISSUE THREAD

**Issue by endquote** [pinry/pinry#63]
I've installed Pinry under ubuntu using the instructions at docker-pinry. I can get it running, but after filling out the user registration form I get a 500 error.

I previously installed it under a different user account using the instructions at ["running on"](https://pinry.readthedocs.org/en/latest/running_on.html) and had the same problem, but since it was a development environment it showed more error detail -- I think it was something like an auth table missing from the database, but I wiped that install.

Is there a log file or something I can check? Or can I turn verbose errors on somehow?

**Comment by overshard** [comment]
It may be that you just needed to run a migrate ``python manage.py migrate`` to get things going.
