### ISSUE TITLE
The admin of this service is not allowing new registrations

### ISSUE THREAD

**Issue by axedesign** [pinry/pinry#78]
`__init__.py` has 
`ALLOW_NEW_REGISTRATIONS = True` but the "Register" page still shows "The admin of this service is not allowing new registrations."

Any idea as to what could cause that?

**Comment by overshard** [comment]
This should be fixed in the latest release, seems to have been an issue with an API update that was done. You may also want to delete your .pyc and restart the server if you experience this still.
