### ISSUE TITLE
Upload failed for images

### ISSUE THREAD

**Issue by Kovah** [pinry/pinry#80]
Hi,
I use the docker image for Pinry and the app is starting but I can't upload images (but the bookmarklet is working).
I get the following errors:
````
POST http://pin.kovah.me/pins/create-image/ 413 (Request Entity Too Large)
[FineUploader] Error when attempting to parse xhr response text (SyntaxError: Unexpected token <)
[FineUploader] Caught exception in 'onComplete' callback - TypeError: Cannot read property 'id' of undefined
````
I already increased the `client_max_body_size ` directive but the error is showing up again and again.

**Comment by overshard** [comment]
I've removed file uploading from the latest release. It's not how I actively use Pinry and we were using an extremely outdated plugin to handle uploads.

**Comment by lapo-luchini** [comment]
Upload was the only way to upload images whose origin need a specific `Referal` header, though…

**Comment by overshard** [comment]
I'll need to use a newer system then.  The code we were using was mostly
broken anyways.

**Comment by overshard** [comment]
I've added a new image upload system in the latest push 8f66cd719c0ff6ccba96856b54093103ca6b524a
