### ISSUE TITLE
Provide a way to exit the bookmarklet

### ISSUE THREAD

**Issue by kevgathuku** [pinry/pinry#81]
When the bookmarklet is open/clicked, there is basically no way to exit it unless the page is refreshed.

It would be convenient to have a way to exit the bookmarlet easily
e.g. by providing a 'close' button or by pressing the 'Escape' button

**Comment by lapo-luchini** [comment]
Yeah, I did that on my branch (but didn't send a PR yet) in commit lapo-luchini/pinry@95878731845ab3f46b2d92d0a79d5120b13811ad

**Comment by kevgathuku** [comment]
Thanks. I'll use this in my fork. 
I hope you eventually send that pull request. 
This is an extremely useful feature that I'm sure would help others facing the same issue.

**Comment by overshard** [comment]
I've pulled this into master, thanks for the update @lapo-luchini
