### ISSUE TITLE
How alive is this project?

### ISSUE THREAD

**Issue by simonv3** [pinry/pinry#90]
If it's alive, will efforts be made to upgrade to a more secure version of Django?

Relevant: #88 #38 

Also, it would be neat to use one of Heroku's one-click deploy buttons to get people up and running quickly on Heroku. I can PR this, but I'd rather do so if there's a chance it will be accepted.

**Comment by supervacuo** [comment]
Pull request to update to Django 1.8 submitted (#91); let's see what the response is..

**Comment by simonv3** [comment]
@supervacuo Awesome, thanks!

**Comment by overshard** [comment]
I'd like to keep it up to date, just got through a few months of some health issues, working on pull requests and updates now.

**Comment by simonv3** [comment]
Thanks for checking in @overshard - hope you're recovering from whatever was ailing you and on the mend!
