### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by magaretha42** [pinry/pinry#92]
It would be really convenient if Pinry supported LDAP servers for user management (not a big fan of multiple user databases).
Django has some built in support for LDAP, so it wouldn't take a lot of work.

**Comment by overshard** [comment]
This isn't something I'm interested in building into the core of Pinry, I'm not a big fan of adding bloated functionality like this for something I think very few people would use. If you want to support LDAP on your own custom implementation that's great, it's an open source project and can be modified however you want.
