### ISSUE TITLE
Bookmarklet Still Opens When Bookmarklet Is Already Open

### ISSUE THREAD

**Issue by voidptr** [pinry/pinry#93]
Silly, but if you've opened the bookmarklet, and then click it again, it'll open another one on-top. Keep clicking, and keeps doing it until your screen eventually goes completely black from all the layered bookmarklets. :)

**Comment by overshard** [comment]
Easy to prevent, could be a problem on slower pages/machines if you click once and don't see it open, I'll fix this.

**Comment by overshard** [comment]
I'm reworking bookmarklets due to the problems surrounding CSP, see issue #96
