### ISSUE TITLE
Problem saving image

### ISSUE THREAD

**Issue by NetThinkTank** [pinry/pinry#94]
What conditions can lead to the "problem saving image" error?  I get that error sometimes even though the images and thumbnails are always saved on the server and in the database.  The pins are not saved when this happens.  Thanks for your help.

**Comment by overshard** [comment]
I'm working on a fix for this, it may be due to file names on the initial save.

**Comment by overshard** [comment]
Latest update might fix this, there were issues with a pull I did to update everything to Django 1.8. Many of the API issues should be fixed.
